name: Build Frontend

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check for frontend changes
        id: changes
        uses: dorny/paths-filter@v3
        with:
          filters: |
            frontend:
              - 'Zadanie_5/**'
              - '.github/workflows/frontend-backend.yml'

      - name: Set up Docker Buildx
        if: steps.changes.outputs.frontend == 'true'
        uses: docker/setup-buildx-action@v3

      - name: Build frontend Docker image
        if: steps.changes.outputs.frontend == 'true'
        run: docker build -t frontend ./Zadanie_5/react-app
