repos:
  - repo: local
    hooks:
      - id: golangci-lint
        name: Run golangci-lint
        entry: bash -c "cd Zadanie_4/project && golangci-lint run --timeout 5m"
        language: system
        types: [go]
        files: ^Zadanie_4/

      - id: run-cypress-tests
        name: Run Cypress tests
        entry: npm run cypress:run
        language: system
        types: [javascript]
        files: ^Zadanie_4/