name: Build Frontend

on:
  workflow_call:
    secrets:
      REACT_APP_API_URL:
        required: true
      EMAIL_USERNAME:
        required: true
      EMAIL_PASSWORD:
        required: true
      CLOUD_SERVER_HOST:
        required: true
      CLOUD_SERVER_USERNAME:
        required: true
      CLOUD_SERVER_SSH_KEY:
        required: true

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check for frontend changes
        id: changes
        uses: dorny/paths-filter@v3
        with:
          filters: |
            frontend:
              - 'Zadanie_5/**'
              - '.github/workflows/frontend-backend.yml'
      
      - name: Create .env file for frontend
        if: steps.changes.outputs.frontend == 'true'
        run: |
          echo "REACT_APP_API_URL=${{ secrets.REACT_APP_API_URL }}" >> Zadanie_5/react-app/.env

      - name: Set up Docker Buildx
        if: steps.changes.outputs.frontend == 'true'
        uses: docker/setup-buildx-action@v3

      - name: Build frontend Docker image
        if: steps.changes.outputs.frontend == 'true'
        run: docker build -t frontend ./Zadanie_5/react-app
      
      - name: Send notification email
        if: steps.changes.outputs.frontend == 'true'
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: Frontend Build Notification
          to: angelo.norelli@student.uj.edu.pl
          from: ${{ secrets.EMAIL_USERNAME }}
          body: "The frontend Docker image has been built successfully."
      
      - name: Prepare SSH key
        if: steps.changes.outputs.backend == 'true'
        run: |
          echo "${{ secrets.CLOUD_SERVER_SSH_KEY }}" > ssh-key-2025-06-07.key
          chmod 400 ssh-key-2025-06-07.key

      - name: Deploy backend to cloud server (rsync)
        if: steps.changes.outputs.backend == 'true'
        run: |
          rsync -avz --relative -e "ssh -i ssh-key-2025-06-07.key -o StrictHostKeyChecking=no" \
            Zadanie_5/react-app docker-compose.yml \
            ${{ secrets.CLOUD_SERVER_USERNAME }}@${{ secrets.CLOUD_SERVER_HOST }}:~
