name: Build Backend

on:
  workflow_call:
    secrets:
      JWT_SECRET_KEY:
        required: true
      GOOGLE_CLIENT_ID:
        required: true
      GOOGLE_CLIENT_SECRET:
        required: true
      GB_CLIENT_ID:
        required: true
      GB_CLIENT_SECRET:
        required: true
      EMAIL_USERNAME:
        required: true
      EMAIL_PASSWORD:
        required: true
      CLOUD_SERVER_HOST:
        required: true
      CLOUD_SERVER_USERNAME:
        required: true
      CLOUD_SERVER_SSH_KEY:
        required: true

jobs:
  build-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check for backend changes
        id: changes
        uses: dorny/paths-filter@v3
        with:
          filters: |
            backend:
              - 'Zadanie_4/**'
              - '.github/workflows/build-backend.yml'
      
      - name: Create .env file for backend
        if: steps.changes.outputs.backend == 'true'
        run: |
          echo "JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }}" >> Zadanie_4/project/.env
          echo "GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}" >> Zadanie_4/project/.env
          echo "GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}" >> Zadanie_4/project/.env
          echo "GITHUB_CLIENT_ID=${{ secrets.GB_CLIENT_ID }}" >> Zadanie_4/project/.env
          echo "GITHUB_CLIENT_SECRET=${{ secrets.GB_CLIENT_SECRET }}" >> Zadanie_4/project/.env

      - name: Set up Docker Buildx
        if: steps.changes.outputs.backend == 'true'
        uses: docker/setup-buildx-action@v3

      - name: Build backend Docker image
        if: steps.changes.outputs.backend == 'true'
        run: docker build -t backend ./Zadanie_4/project

      - name: Send notification email
        if: steps.changes.outputs.backend == 'true'
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: Backend Build Notification
          to: angelo.norelli@student.uj.edu.pl
          from: ${{ secrets.EMAIL_USERNAME }}
          body: "The backend Docker image has been built successfully."

      - name: Prepare SSH key
        if: steps.changes.outputs.backend == 'true'
        run: |
          echo "${{ secrets.CLOUD_SERVER_SSH_KEY }}" > ssh-key-2025-06-07.key
          chmod 400 ssh-key-2025-06-07.key

      - name: Deploy backend to cloud server (rsync)
        if: steps.changes.outputs.backend == 'true'
        run: |
          rsync -avz --relative -e "ssh -i ssh-key-2025-06-07.key -o StrictHostKeyChecking=no" \
            Zadanie_4/project docker-compose.yml \
            ${{ secrets.CLOUD_SERVER_USERNAME }}@${{ secrets.CLOUD_SERVER_HOST }}:~