name: Build Backend

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check for backend changes
        id: changes
        uses: dorny/paths-filter@v3
        with:
          filters: |
            backend:
              - 'Zadanie_4/**'
              - '.github/workflows/build-backend.yml'
      
      - name: Create .env file for backend
        if: steps.changes.outputs.backend == 'true'
        run: |
          echo "JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }}" >> Zadanie_4/project/.env
          echo "GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}" >> Zadanie_4/project/.env
          echo "GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}" >> Zadanie_4/project/.env
          echo "GITHUB_CLIENT_ID=${{ secrets.GB_CLIENT_ID }}" >> Zadanie_4/project/.env
          echo "GITHUB_CLIENT_SECRET=${{ secrets.GB_CLIENT_SECRET }}" >> Zadanie_4/project/.env

      - name: Set up Docker Buildx
        if: steps.changes.outputs.backend == 'true'
        uses: docker/setup-buildx-action@v3

      - name: Build backend Docker image
        if: steps.changes.outputs.backend == 'true'
        run: docker build -t backend ./Zadanie_4/project

      - name: Send notification email
        if: steps.changes.outputs.backend == 'true'
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: Backend Build Notification
          to: angelo.norelli@student.uj.edu.pl
          from: ${{ secrets.EMAIL_USERNAME }}
          body: "The backend Docker image has been built successfully."
      
      - name: Deploy backend to cloud server
        if: success()
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.CLOUD_SERVER_HOST }}
          username: ${{ secrets.CLOUD_SERVER_USERNAME }}
          key: ${{ secrets.CLOUD_SERVER_SSH_KEY }}
          source: "./Zadanie_4/project"
          target: "~"
      
      - name: Restart app on server
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.CLOUD_SERVER_HOST }}
          username: ${{ secrets.CLOUD_SERVER_USERNAME }}
          key: ${{ secrets.CLOUD_SERVER_SSH_KEY }}
          script: |
            docker-compose up --build -d
          command_timeout: 90m
          timeout: 5m